### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by greenmotion** [langflow-ai/langflow-embedded-chat#28]
I'm probably doing something wrong here, but after compiling and using the embedded-chat, I get the following error in my browser's debugger:

Uncaught SyntaxError: Invalid regular expression: /^["'*`ÂªÂ°Â²-Â´Â¹Âºâ€˜-â€Ÿâ€²-â€·â—â°â±â´-â¿â‚€-â‚Ž]+$/: Range out of order in character class (at bundle.min.js:1:83676)
    at new RegExp (<anonymous>)
    at 5 (bundle.min.js:1:83676)
    at r (bundle.min.js:1:96)
    at 5781 (bundle.min.js:1:682892)
    at r (bundle.min.js:1:96)
    at 2479 (bundle.min.js:1:653163)
    at r (bundle.min.js:1:96)
    at 1661 (bundle.min.js:1:652919)
    at r (bundle.min.js:1:96)
    at 9759 (bundle.min.js:1:633100)

What am I missing?

Thank you!

  GM

**Comment by greenmotion** [comment]
User error. In case this might be of help to anyone, I had to set Content-Type in the HTML page to utf-8, like so.

`<meta http-equiv="Content-Type" content="text/html; charset=utf-8">`
